import Icons from "@taroify/icons";
export const TaroifyIcons = [
  {
    title: "基础图标",
    icons: {
      Arrow: Icons.Arrow,
      ArrowLeft: Icons.ArrowLeft,
      ArrowUp: Icons.ArrowUp,
      ArrowDown: Icons.ArrowDown,
      Success: Icons.Success,
      Cross: Icons.Cross,
      Plus: Icons.Plus,
      Minus: Icons.Minus,
      Fail: Icons.Fail,
      Circle: Icons.Circle,
    },
  },
  {
    title: "线框风格",
    icons: {
      LocationOutlined: Icons.LocationOutlined,
      LikeOutlined: Icons.LikeOutlined,
      StarOutlined: Icons.StarOutlined,
      PhoneOutlined: Icons.PhoneOutlined,
      SettingOutlined: Icons.SettingOutlined,
      FireOutlined: Icons.FireOutlined,
      CouponOutlined: Icons.CouponOutlined,
      CartOutlined: Icons.CartOutlined,
      ShoppingCartOutlined: Icons.ShoppingCartOutlined,
      CartCircleOutlined: Icons.CartCircleOutlined,
      FriendsOutlined: Icons.FriendsOutlined,
      CommentOutlined: Icons.CommentOutlined,
      GemOutlined: Icons.GemOutlined,
      GiftOutlined: Icons.GiftOutlined,
      PointGiftOutlined: Icons.PointGiftOutlined,
      SendGiftOutlined: Icons.SendGiftOutlined,
      ServiceOutlined: Icons.ServiceOutlined,
      BagOutlined: Icons.BagOutlined,
      TodoListOutlined: Icons.TodoListOutlined,
      BalanceListOutlined: Icons.BalanceListOutlined,
      Close: Icons.Close,
      ClockOutlined: Icons.ClockOutlined,
      QuestionOutlined: Icons.QuestionOutlined,
      Passed: Icons.Passed,
      AddOutlined: Icons.AddOutlined,
      GoldCoinOutlined: Icons.GoldCoinOutlined,
      InfoOutlined: Icons.InfoOutlined,
      PlayCircleOutlined: Icons.PlayCircleOutlined,
      PauseCircleOutlined: Icons.PauseCircleOutlined,
      StopCircleOutlined: Icons.StopCircleOutlined,
      WarningOutlined: Icons.WarningOutlined,
      PhoneCircleOutlined: Icons.PhoneCircleOutlined,
      MusicOutlined: Icons.MusicOutlined,
      SmileOutlined: Icons.SmileOutlined,
      ThumbCircleOutlined: Icons.ThumbCircleOutlined,
      CommentCircleOutlined: Icons.CommentCircleOutlined,
      BrowsingHistoryOutlined: Icons.BrowsingHistoryOutlined,
      UnderwayOutlined: Icons.UnderwayOutlined,
      MoreOutlined: Icons.MoreOutlined,
      VideoOutlined: Icons.VideoOutlined,
      ShopOutlined: Icons.ShopOutlined,
      ShopCollectOutlined: Icons.ShopCollectOutlined,
      ShareOutlined: Icons.ShareOutlined,
      ChatOutlined: Icons.ChatOutlined,
      SmileCommentOutlined: Icons.SmileCommentOutlined,
      VipCardOutlined: Icons.VipCardOutlined,
      AwardOutlined: Icons.AwardOutlined,
      DiamondOutlined: Icons.DiamondOutlined,
      VolumeOutlined: Icons.VolumeOutlined,
      ClusterOutlined: Icons.ClusterOutlined,
      WapHomeOutlined: Icons.WapHomeOutlined,
      PhotoOutlined: Icons.PhotoOutlined,
      GiftCardOutlined: Icons.GiftCardOutlined,
      ExpandOutlined: Icons.ExpandOutlined,
      MedalOutlined: Icons.MedalOutlined,
      GoodJobOutlined: Icons.GoodJobOutlined,
      ManagerOutlined: Icons.ManagerOutlined,
      LabelOutlined: Icons.LabelOutlined,
      BookmarkOutlined: Icons.BookmarkOutlined,
      BillOutlined: Icons.BillOutlined,
      HotOutlined: Icons.HotOutlined,
      HotSaleOutlined: Icons.HotSaleOutlined,
      NewOutlined: Icons.NewOutlined,
      NewArrivalOutlined: Icons.NewArrivalOutlined,
      GoodsCollectOutlined: Icons.GoodsCollectOutlined,
      EyeOutlined: Icons.EyeOutlined,
    },
  },
  {
    title: "实底风格",
    icons: {
      Location: Icons.Location,
      Like: Icons.Like,
      Star: Icons.Star,
      Phone: Icons.Phone,
      Setting: Icons.Setting,
      Fire: Icons.Fire,
      Coupon: Icons.Coupon,
      Cart: Icons.Cart,
      ShoppingCart: Icons.ShoppingCart,
      CartCircle: Icons.CartCircle,
      Friends: Icons.Friends,
      Comment: Icons.Comment,
      Gem: Icons.Gem,
      Gift: Icons.Gift,
      PointGift: Icons.PointGift,
      SendGift: Icons.SendGift,
      Service: Icons.Service,
      Bag: Icons.Bag,
      TodoList: Icons.TodoList,
      BalanceList: Icons.BalanceList,
      Clear: Icons.Clear,
      Clock: Icons.Clock,
      Question: Icons.Question,
      Checked: Icons.Checked,
      Add: Icons.Add,
      GoldCoin: Icons.GoldCoin,
      Info: Icons.Info,
      PlayCircle: Icons.PlayCircle,
      PauseCircle: Icons.PauseCircle,
      StopCircle: Icons.StopCircle,
      Warning: Icons.Warning,
      PhoneCircle: Icons.PhoneCircle,
      Music: Icons.Music,
      Smile: Icons.Smile,
      ThumbCircle: Icons.ThumbCircle,
      CommentCircle: Icons.CommentCircle,
      BrowsingHistory: Icons.BrowsingHistory,
      Underway: Icons.Underway,
      More: Icons.More,
      Video: Icons.Video,
      Shop: Icons.Shop,
      ShopCollect: Icons.ShopCollect,
      Share: Icons.Share,
      Chat: Icons.Chat,
      SmileComment: Icons.SmileComment,
      VipCard: Icons.VipCard,
      Award: Icons.Award,
      Diamond: Icons.Diamond,
      Volume: Icons.Volume,
      Cluster: Icons.Cluster,
      WapHome: Icons.WapHome,
      Photo: Icons.Photo,
      GiftCard: Icons.GiftCard,
      Expand: Icons.Expand,
      Medal: Icons.Medal,
      GoodJob: Icons.GoodJob,
      Manager: Icons.Manager,
      Label: Icons.Label,
      Bookmark: Icons.Bookmark,
      Bill: Icons.Bill,
      Hot: Icons.Hot,
      HotSale: Icons.HotSale,
      New: Icons.New,
      NewArrival: Icons.NewArrival,
      GoodsCollect: Icons.GoodsCollect,
    },
  },
];

export const AllTaroifyIconsKey = TaroifyIcons.flatMap((item) =>
  Object.keys(item.icons)
);

export default TaroifyIcons.reduce((acc, cur) => {
  const icons = cur.icons;
  Object.keys(icons).forEach((iconName) => {
    acc[iconName] = icons[iconName];
  });
  return acc;
}, {});
